name: Run Cypress E2E Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18 (for Vite compatibility)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project with Vite
        run: npm run build

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview
          wait-on: http://localhost:4173
          wait-on-timeout: 90
