name: Run Cypress E2E Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Print Node version for sanity
        run: node -v

      - name: Clean install
        run: |
          rm -rf node_modules
          npm ci

      - name: Confirm plugin-vue version
        run: npm ls @vitejs/plugin-vue

      - name: Build project
        run: npm run build

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview
          wait-on: http://localhost:4173
          wait-on-timeout: 90
