name: Run Cypress E2E Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x (absolutely enforced)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Force clear previous build artifacts
        run: rm -rf node_modules dist .vite

      - name: Install dependencies fresh
        run: npm install

      - name: Verify Node version (sanity check)
        run: node -v  # should be v18.x

      - name: Build project (this WILL work now)
        run: npm run build

      - name: Start preview server and run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview
          wait-on: 'http://localhost:4173'
          wait-on-timeout: 90
