name: Run Cypress E2E Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18 (force exact match, no cache)
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'
          check-latest: true

      - name: Verify Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run preview
          wait-on: http://localhost:4173
          wait-on-timeout: 90
